Repository parameter1/industrial-media-websites, pull requests merged in 2022-03, with the labels that each got.

#179 Do not defer gam and gtm
  packages/shared/components/document.marko
Labels: 🌐 site: ALL

#180 Upgrade dependencies
  packages/shared/package.json
  yarn.lock
Labels: 🌐 site: ALL

#181 Create new microsite MDD
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  docker-compose.yml
  sites/medicaldesigndevelopment.com/browser/.eslintrc.js
  sites/medicaldesigndevelopment.com/browser/index.js
  sites/medicaldesigndevelopment.com/config/core.js
  sites/medicaldesigndevelopment.com/config/gam.js
  sites/medicaldesigndevelopment.com/config/identity-x.js
  sites/medicaldesigndevelopment.com/config/native-x.js
  sites/medicaldesigndevelopment.com/config/navigation.js
  sites/medicaldesigndevelopment.com/config/site.js
  sites/medicaldesigndevelopment.com/config/social-links.js
  sites/medicaldesigndevelopment.com/index.js
  sites/medicaldesigndevelopment.com/newrelic.js
  sites/medicaldesigndevelopment.com/package.json
  sites/medicaldesigndevelopment.com/server/public/robots.txt
  sites/medicaldesigndevelopment.com/server/routes/content.js
  sites/medicaldesigndevelopment.com/server/routes/dynamic-page.js
  sites/medicaldesigndevelopment.com/server/routes/home.js
  sites/medicaldesigndevelopment.com/server/routes/index.js
  sites/medicaldesigndevelopment.com/server/routes/search.js
  sites/medicaldesigndevelopment.com/server/routes/website-section.js
  sites/medicaldesigndevelopment.com/server/styles/index.scss
  sites/medicaldesigndevelopment.com/server/templates/index.marko
  yarn.lock
Labels: help wanted

#185 Add bc floating player
  packages/shared/browser/floating-video-player.vue
  packages/shared/browser/index.js
  packages/shared/components/elements/video-player.marko
  packages/shared/components/layouts/published-content.marko
  packages/shared/components/layouts/website-section/default.marko
  packages/shared/components/marko.json
  packages/shared/package.json
  packages/shared/templates/content/index.marko
  packages/shared/templates/dynamic-page/index.marko
  yarn.lock
Labels: 🌐 site: ALL

#190 Update ‘advertise’ link
  sites/medicaldesigndevelopment.com/config/navigation.js
Labels: 🌐 site: medicaldesigndevelopment.com
